version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: /home/ec2-user/deploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /home/ec2-user/deploy/after_install.sh
      timeout: 300
runas: root
